"""Data models for PowerPoint presentation automation."""
from __future__ import annotations
from typing import List, Optional, Dict, Any, Literal
from pydantic import BaseModel, Field


class SlideItem(BaseModel):
    title: str
    subtitle: Optional[str] = None
    slide_type: Literal[
        "title",
        "agenda",
        "content",
        "two_column",
        "stats",
        "comparison",
        "conclusion"
    ] = "content"
    bullets: List[str] = Field(default_factory=list)
    left_heading: Optional[str] = None
    left_bullets: List[str] = Field(default_factory=list)
    right_heading: Optional[str] = None
    right_bullets: List[str] = Field(default_factory=list)
    stats: List[Dict[str, str]] = Field(default_factory=list)  # e.g. [{"value": "85%", "label": "Growth Rate"}]
    key_takeaway: Optional[str] = None
    notes: Optional[str] = None
    image_path: Optional[str] = None
    image_caption: Optional[str] = None
    image_query: Optional[str] = None


class PresentationData(BaseModel):
    title: str
    subtitle: Optional[str] = "Generated by NEXUS AI"
    topic: str
    theme: str = "executive_navy"  # executive_navy, modern_dark, tech_indigo, emerald_green, corporate_light
    slides: List[SlideItem] = Field(default_factory=list)
    footer: Optional[str] = "NEXUS Presentation"
    include_images: bool = True


class PresentationStats(BaseModel):
    slide_count: int
    title: str
    topic: str
    theme: str
    slide_titles: List[str] = Field(default_factory=list)
    file_path: Optional[str] = None
