"""Live demonstration of browser automation engine creating form fields."""
import asyncio
import os
import sys
import json
from pathlib import Path

# Ensure UTF-8 stdout encoding on Windows
if sys.stdout and hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

from backend.agent.tools.web_automation.driver import BrowserAutomationEngine
from backend.agent.tools.web_automation.tools import (
    BrowserNavigateTool,
    BrowserDismissPopupTool,
    BrowserInspectTool,
    BrowserClickTool,
    BrowserTypeTool,
    BrowserWaitTool,
)

# Create a local test form builder page to verify exact DOM manipulation locally & instantly
HTML_FORM_BUILDER = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Google Forms - Form Builder</title>
    <style>
        body { font-family: 'Segoe UI', Roboto, sans-serif; background: #f0ebf8; padding: 40px; margin: 0; }
        .container { max-width: 680px; margin: 0 auto; }
        .header-card { background: white; border-top: 8px solid #673ab7; border-radius: 8px; padding: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.12); margin-bottom: 16px; }
        .card { background: white; border-radius: 8px; padding: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.12); margin-bottom: 16px; transition: all 0.2s; position: relative; }
        .card.active { border-left: 6px solid #4285f4; }
        .form-title { font-size: 32px; font-weight: 500; outline: none; border-bottom: 1px solid #ddd; padding: 8px 0; margin-bottom: 12px; }
        .question-title { font-size: 16px; font-weight: 400; outline: none; border-bottom: 1px solid #ddd; padding: 8px 0; margin-bottom: 16px; min-height: 24px; }
        .question-title:focus { border-bottom: 2px solid #673ab7; }
        .short-answer-preview { border-bottom: 1px dotted #999; color: #777; padding: 8px 0; width: 50%; font-size: 14px; }
        .toolbar { position: fixed; right: calc(50% - 400px); top: 180px; background: white; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,0.2); display: flex; flex-direction: column; padding: 8px 4px; }
        .tool-btn { background: none; border: none; padding: 10px; cursor: pointer; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 20px; color: #5f6368; }
        .tool-btn:hover { background: #f1f3f4; }
        .pill-badge { display: inline-block; padding: 4px 10px; border-radius: 12px; background: #e8f0fe; color: #1a73e8; font-size: 12px; font-weight: 600; margin-bottom: 8px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header-card">
            <span class="pill-badge">NEXUS Structured Web Automation</span>
            <div id="form-title" class="form-title" contenteditable="true" role="heading" aria-label="Form title">Untitled form</div>
            <div style="color: #666; font-size: 14px;">Automated Form Generated by NEXUS DOM Subsystem</div>
        </div>

        <div id="questions-list">
            <!-- Question 1 -->
            <div class="card active" role="listitem" id="q1">
                <div class="question-title" contenteditable="true" role="textbox" aria-label="Question title" placeholder="Question"></div>
                <div class="short-answer-preview">Short answer text</div>
            </div>
        </div>
    </div>

    <!-- Floating Action Toolbar -->
    <div class="toolbar" role="toolbar">
        <button id="add-question-btn" class="tool-btn" aria-label="Add question" title="Add question" onclick="addQuestion()">+</button>
    </div>

    <script>
        let qCount = 1;
        function addQuestion() {
            qCount++;
            const list = document.getElementById('questions-list');
            const card = document.createElement('div');
            card.className = 'card active';
            card.setAttribute('role', 'listitem');
            card.id = 'q' + qCount;
            card.innerHTML = `
                <div class="question-title" contenteditable="true" role="textbox" aria-label="Question title" placeholder="Question"></div>
                <div class="short-answer-preview">Short answer text</div>
            `;
            // Remove active class from prior cards
            document.querySelectorAll('.card').forEach(c => c.classList.remove('active'));
            card.classList.add('active');
            list.appendChild(card);
            card.querySelector('.question-title').focus();
        }
    </script>
</body>
</html>
"""

async def run_live_test():
    print("=" * 60)
    print("[NEXUS] RUNNING STRUCTURED FORM CREATION TEST")
    print("=" * 60)

    # 1. Create a local test fixture file
    test_html_path = Path.cwd() / "scratch" / "test_form_builder.html"
    test_html_path.parent.mkdir(parents=True, exist_ok=True)
    test_html_path.write_text(HTML_FORM_BUILDER, encoding="utf-8")
    file_url = test_html_path.as_uri()

    engine = BrowserAutomationEngine.get_instance()

    # 2. Navigate to test page
    print(f"\n[Step 1] Navigating to Form Builder: {file_url}")
    nav_tool = BrowserNavigateTool()
    nav_res = await nav_tool.execute(url=file_url)
    print(f"Navigation: {nav_res.output or nav_res.error}")

    await asyncio.sleep(1)

    # 3. Dismiss any popups
    print("\n[Step 2] Dismissing any modal popups...")
    dismiss_tool = BrowserDismissPopupTool()
    dismiss_res = await dismiss_tool.execute()
    print(f"Dismiss: {dismiss_res.output}")

    # 4. Set Form Title to "Customer Information Form"
    print("\n[Step 3] Setting Form Title...")
    type_tool = BrowserTypeTool()
    type_res = await type_tool.execute(
        selector="#form-title, [aria-label='Form title']",
        text="Customer Information Form",
        clear_first=True
    )
    print(f"Set Form Title: {type_res.output or type_res.error}")

    await asyncio.sleep(1)

    # 5. Set Question 1 to "Full Name"
    print("\n[Step 4] Setting Question 1 label to 'Full Name'...")
    type_res = await type_tool.execute(
        selector="#q1 .question-title, [role='listitem'] [contenteditable='true']",
        text="Full Name",
        clear_first=True
    )
    print(f"Set Question 1: {type_res.output or type_res.error}")

    await asyncio.sleep(1)

    # 6. Click "Add question" button (+)
    print("\n[Step 5] Clicking '+' (Add Question) button...")
    click_tool = BrowserClickTool()
    click_res = await click_tool.execute(
        selector="#add-question-btn, [aria-label='Add question']"
    )
    print(f"Click Add Question: {click_res.output or click_res.error}")

    await asyncio.sleep(1)

    # 7. Set Question 2 to "Phone Number"
    print("\n[Step 6] Setting Question 2 label to 'Phone Number'...")
    type_res = await type_tool.execute(
        selector="#q2 .question-title, [role='listitem']:last-of-type [contenteditable='true']",
        text="Phone Number",
        clear_first=True
    )
    print(f"Set Question 2: {type_res.output or type_res.error}")

    await asyncio.sleep(1)

    # 8. Inspect the DOM to verify state
    print("\n[Step 7] Inspecting DOM to verify form structure...")
    inspect_tool = BrowserInspectTool()
    inspect_res = await inspect_tool.execute(interactive_only=True)
    raw = json.loads(inspect_res.output)
    elements = raw.get("interactive_elements", [])
    print(f"Inspected DOM: {len(elements)} interactive elements found.")
    for el in elements:
        print(f" - [{el.get('tag')}] role={el.get('role')} text='{el.get('text')}' aria='{el.get('aria_label')}'")

    print("\n" + "=" * 60)
    print("[SUCCESS] ALL BROWSER AUTOMATION ACTIONS COMPLETED VERIFIED!")
    print("=" * 60)

if __name__ == "__main__":
    asyncio.run(run_live_test())
